import type { Metadata } from "next";
import { Rammetto_One } from "next/font/google";
import "./globals.css";

const rammettoOne = Rammetto_One({ weight: ["400"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rammettoOne.className}>{children}</body>
    </html>
  );
}
